---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-app-develop
bases:
- ../../base
images:
- name: agotfrid/python-app
  newName: agotfrid/python-app
  newTag: "076a9536761a2d9e8394591001062081d630edb7"
resources:
- app-env-configmap.yaml
- app-env-secret.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- pv.yaml
- pvc.yaml
patchesStrategicMerge:
- set-replicas.yaml
