---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-app-develop
bases:
- ../../base
images:
- name: agotfrid/python-app
  newName: agotfrid/python-app
  newTag: "12ff3152952adb4e1e1ce3eaadf0879d9e3c3342"
resources:
- app-env-configmap.yaml
- app-env-secret.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- pv.yaml
- pvc.yaml
patchesStrategicMerge:
- set-replicas.yaml
